### PR TITLE
changing cp.x into kcp.x

### PR DESCRIPTION
**Pull request by degennar**
I simply modified every string matching `cp.x` into `kcp.x`.

### CODE REVIEW

**Comment by degennar** [comment]
Did the same in `python_KI`. As soon you approve this I will align with this again and commit the changes directly in my open PR on `python-KI`.

**Review by elinscott — COMMENTED** [review]
Looks good, thanks for doing this. Perhaps we should also rename `espresso_cp.py` to `espresso_kcp.py`? Although that would mess with all of our `from ase.io import espresso_cp` commands elsewhere... what do you reckon?

**Comment by degennar** [comment]
Yeah I thought the same while I was going through that. Honestly I don't know.. in the end `espresso_cp` did not exist in `ASE` so it is something created specifically for the koopmans CP code and so we could even change the name into `espresso_kcp`. Anyway I don't think it is strictly necessary right now so maybe we can keep it like that for the moment and then eventually change it later.. But I am happy both ways, so I know that I am passing the buck but I would leave to you the final decision!

**Review by elinscott — APPROVED** [review]
This is now all working, thanks for setting this up!

**Pull request merged**
